### ISSUE TITLE
【OI系統申請需求單】1.F128_於STDF_MIR中判斷CMOD_CODE需求  2.F128_STDF_更名需求

### ISSUE THREAD

**Issue by whooes** [Sigurd-Hukou/CredenceDX-OI#93]
[【OI系統申請需求單】1 F128_於STDF_MIR中判斷CMOD_CODE需求  2 F128_STDF_更名需求.zip](https://github.com/Sigurd-Hukou/CredenceDX-OI/files/4893900/OI.1.F128_.STDF_MIR.CMOD_CODE.2.F128_STDF_.zip)

F128 (Microchip)客戶有兩個需求,請幫忙確認是否可行,謝謝

Case1: F128_於STDF_MIR中,從CMOD_COD欄位判斷是量產批或工程批
先前有提出申請如附件,現在是希望改從MIR開檔資訊中裡的CMOD_COD判斷是否為工程批或量產批
請再幫忙確認是否可行,謝謝

平台: D10、DX
目的: 從CMOD_COD中判斷出是量產批或工程批
 

Case2: F128_STDF_更名需求
客戶希望更新STDF naming rule,請參考如下
請再幫忙確認是否可行,謝謝

現今規則:  Lot Number_站點_程式名稱_型號_日期.std.gz 
Ex: ASE-211000186.000_FT1-02_DARR83_D10_quad_rv_a2b_WYY0192HXA0C_20200617033512.std.gz

後續須更新成:  Lot Number_程式名稱_型號_日期_站點.std.gz

平台: D10
目的: STDF file更名成客戶命名規則

Thanks!
Nicole_Wu

**Comment by whooes** [comment]
Case1 : TestProgData.CommandMode

**Comment by Colara** [comment]
7/15 TestProgData.CommandMode此command沒使用過 , 上機驗證確定STDF有寫入 , TryRun後即可上線
![image](https://user-images.githubusercontent.com/34740615/87539451-7d8b4d80-c6d0-11ea-9602-48fbac45aaae.png)
